spring.application.name=Proyectodat

#CONEXION A MYSQL

sprint.datasource.url=
sprint.datasource.username =
sprint.datasource.password =
sprint.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#PUERTO DEL SERVIDOR

server.port=8080